"""
report_generator.py — LLM-powered draft radiology report generator

Uses the Anthropic API directly via requests (bypasses SDK encoding issues).
Requires ANTHROPIC_API_KEY environment variable.

For research/demo purposes only — not for clinical use.
"""

import json
import os

import requests

# ── Prompt templates (ASCII-only) ────────────────────────────────────────────
_SYSTEM_PROMPT = (
    "You are an AI assistant helping generate draft chest X-ray report summaries "
    "based on automated image classification results. Your role is to translate "
    "model outputs into structured, readable draft text.\n\n"
    "You must always:\n"
    "1. Clearly state this is AI-generated and not a clinical diagnosis\n"
    "2. Use professional but accessible language\n"
    "3. Be concise -- clinicians are busy\n"
    "4. Reflect the model confidence level in your language choices\n"
    "   (e.g., high confidence: findings are consistent with, "
    "low confidence: cannot exclude, consider)\n"
    "5. Respond in English only. Use ASCII characters only.\n\n"
    "You must never:\n"
    "- Make definitive clinical diagnoses\n"
    "- Recommend specific treatments\n"
    "- Omit the disclaimer"
)

_REPORT_PROMPT = (
    "The AI chest X-ray classifier produced the following results:\n\n"
    "Primary prediction: {prediction}\n"
    "Confidence: {confidence:.1%}\n\n"
    "Full probability distribution:\n"
    "{prob_lines}\n\n"
    "Please generate a structured draft report with exactly these three sections:\n\n"
    "FINDINGS:\n"
    "[1-2 sentences describing what the model detected, referencing confidence level]\n\n"
    "IMPRESSION:\n"
    "[1 sentence clinical interpretation, appropriately hedged for an AI draft]\n\n"
    "PATIENT SUMMARY:\n"
    "[2-3 sentences in plain language a patient could understand]\n\n"
    "End with this exact line:\n"
    "WARNING: This report was generated by an AI model for research/demo purposes "
    "only and is NOT a clinical diagnosis. Always consult a qualified radiologist."
)

_API_URL = "https://api.anthropic.com/v1/messages"
_MODEL = "claude-sonnet-4-6"


def generate_report(
    prediction: str,
    confidence: float,
    probabilities: dict,
) -> str:
    """
    Call the Anthropic API directly to generate a draft radiology report.

    Returns an ASCII-safe draft report string.
    Raises EnvironmentError if ANTHROPIC_API_KEY is not set.
    """
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        raise EnvironmentError(
            "ANTHROPIC_API_KEY environment variable is not set."
        )

    prob_lines = "\n".join(
        f"  - {label}: {prob:.1%}"
        for label, prob in sorted(probabilities.items(), key=lambda x: -x[1])
    )

    user_message = _REPORT_PROMPT.format(
        prediction=prediction,
        confidence=confidence,
        prob_lines=prob_lines,
    )

    payload = {
        "model": _MODEL,
        "max_tokens": 1024,
        "system": _SYSTEM_PROMPT,
        "messages": [{"role": "user", "content": user_message}],
    }

    # Encode payload as UTF-8 bytes to avoid any system-level ASCII codec issues
    payload_bytes = json.dumps(payload, ensure_ascii=True).encode("utf-8")

    response = requests.post(
        _API_URL,
        headers={
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        },
        data=payload_bytes,
        timeout=30,
    )
    response.raise_for_status()

    # Parse response from raw bytes — never let Python touch the text as ASCII
    data = json.loads(response.content.decode("utf-8", errors="replace"))
    raw_text = data["content"][0]["text"]

    # Strip any non-ASCII characters before returning
    return raw_text.encode("ascii", errors="ignore").decode("ascii")